### ISSUE TITLE
How to provide search through all option and group name?

### ISSUE THREAD

**Issue by pankovOleksandr** [lordfriend/nya-bootstrap-select#162]
Hi, is it a way to provide search not only by the items but also by group names?
What can I try to implement this?
I can do it by placing additional span with group name and visibility: none. But I don't think it's good decision.

![geo](https://cloud.githubusercontent.com/assets/10296279/25282100/26c50a92-26b8-11e7-8e7a-397ff09733f3.png)

**Comment by lordfriend** [comment]
Due to the primitive design of the search. It is not very easy to implement without break the current function
The search is actually transverse the dom tree of option menu. which make it a little inflexible for these kind of change.
https://github.com/lordfriend/nya-bootstrap-select/blob/master/src/nya-bs-public.js#L284
