### ISSUE TITLE
Support for binding actions-box, multiple, live-search

### ISSUE THREAD

**Issue by rsmithsa** [lordfriend/nya-bootstrap-select#166]
I've run into an issue where I'm creating multiple selectors in an ng-repeat, something like this (with the irrelevant details removed):
```
<div ng-repeat="filterItem in vm.filters">
  <ol class="nya-bs-select"  ng-attr-multiple="{{filterItem.enableMultiSelect || undefined}}" actions-box="{{filterItem.enableMultiSelect || 'false'}}" >
    <li nya-bs-option="item in filterItem.items track by item.Id" data-value="item.Id"></li>
  </ol>
</div>
```

This doesn't work and after digging into the code a bit it seems as if the setup for the actions-box and live-search take place in the compile phase which only occurs once. So all the selectors get the same config effectively.

I'd also expect something like this (borrowing your sample code) to not work as expected (i.e. not using ng-repeat):

```
<form class="form-inline">
  <!-- title on nya-bs-select -->
  <ol class="nya-bs-select" ng-model="model" actions-box="true" multiple>
    <li nya-bs-option="option in arrayCollection">
      <a>
        {{ option.name }}
        <span class="glyphicon glyphicon-ok check-mark"></span>
      </a>
    </li>
  </ol>

  <ol class="nya-bs-select" ng-model="model" actions-box="false" multiple>
    <li nya-bs-option="option in arrayCollection">
      <a>
        {{ option.name }}
        <span class="glyphicon glyphicon-ok check-mark"></span>
      </a>
    </li>
  </ol>
</form>
```

I've forked and made a temporary fix which still creates the various action-box & search elements in the compile phase (only if the respective attributes exist) but hides/shows them in the link function.

I'll submit a pull request (probably not production ready) for review and testing.

**Comment by lordfriend** [comment]
At the early time for refactoring this project, I simply not expect to support all attributes as one-way binding, because I don't want to watch so many attribute and make a lot of state inside this directive.

So I only suggest to use an `ng-if` or `ng-switch` out of the nya-bs-select directive if you have some property which is controlled by one-way binding property.

But maybe your solution can be considered if It doesn't break the old code

**Comment by peterjhart** [comment]
@rsmithsa The result of PR 167 is that the live search and actions box will show for all defined values, including `'false'`. Furthermore, I don't understand how that PR fixes the problem you encountered.

My first thought is to add `track by` to your loop through `vm.filters`:

```
<div ng-repeat="filterItem in vm.filters track by filterItem.someUniqueProperty">
    …
</div>
```

This would replace the item elements instead of reusing them, which I think is the cause of your problem.

**Comment by rsmithsa** [comment]
It definitely fixes our issue, see my comments on the PR: https://github.com/lordfriend/nya-bootstrap-select/pull/167#discussion_r123676862

I did add the disclaimer that it's probably not production ready, so my apologies if I've broken some other use case.
